<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Stocks\EventHandlers\StockIncreasedHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory_Management_Platform.Contracts\Inventory_Management_Platform.Contracts.csproj" />
    <ProjectReference Include="..\Inventory_Management_Platform_Domain\Inventory_Management_Platform.Domain.csproj" />
  </ItemGroup>

</Project>
